name: Deploy
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build tests
        run: docker build -t grszyman/docker-react-2022-dev -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true grszyman/docker-react-2022-dev npm test

      - name: Echo ref
        run: echo ${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build production
        run: docker build -t grszyman/docker-react-2022:v${{ github.sha }} -t grszyman/docker-react-2022:latest .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react-2022
          environment_name: Dockerreact2022-env
          existing_bucket_name: elasticbeanstalk-us-east-2-840579016403
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip