name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build tests
        run: docker build -t grszyman/docker-react-2022 -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true grszyman/docker-react-2022 npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'